---
configuration_directory: "%{cwd}/examples/full"
state_file: "%{cwd}/state/full.tfstate"
vars:
  region: "%{hiera('region')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  stream_name: "%{hiera('component')}-%{hiera('deployment_identifier')}"
